# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Serafin Dinges
email: hi@serafindinges.com
subtitle: >- # this means to ignore newlines until "baseurl:"
  Journalist, Producer & Programmer
description: >-
  <p>
  I'm a freelance journalist, podcast producer and programmer. I did a degree in Comparative Literature and English Linguistics, got lost, graduated, found my passion, and am now doing a postgrad in Cultural Journalism.
  </p><p>
  I mainly work in podcasts where I host, produce, research, edit, consult. I'm interested in the internet, science communication, data journalism. I also work in writing where I mostly stare at an empty screen. 
  </p><p>
  My work is in English and German and has been done for <em>radioeins, rbb, Gabor Steingarts Morning Briefing, Reform Radio, Frankfurter Rundschau</em> and lots underfunded podcast projects.
  </p><p>
    <a href=/assets/docs/CV_SerafinDinges_DE.pdf target=_blank>Curriculum Vitae</a> | 
    <a href=/assets/docs/CV_SerafinDinges_EN.pdf target=_blank>Lebenslauf</a>
  </p>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://serafindinges.com" # the base hostname & protocol for your site, e.g. http://example.com
icon: /assets/images/icon-512.png
google_analytics: UA-50812661-2
twitter_username: etherealserafin
github_username:  SerafinDinges

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "/page/:num/"